### ISSUE TITLE
What's the correct way to use this package?

### ISSUE THREAD

**Issue by edyu** [MommaWatasu/OteraEngine.jl#14]
It looks like
<pre>
tmp = Template("./my_template.html")
init = Dict("name" => "blah")
return html(tmp(init))
</pre>
doesn't work anymore (will not find the function)
I have to now do
<pre>
tmp = Template("./my_template.html")
init = Dict("name" => "blah")
return html(tmp(; tmp_init=init))
</pre>

**Comment by MommaWatasu** [comment]
There was a lack of explanation. As I create template code, you have to use not `init` but `jl_init` and `tmp_init`.
I think [this issue](https://github.com/MommaWatasu/OteraEngine.jl/issues/13) has been solved as well.

**Comment by edyu** [comment]
You still have some inline example code pointing to the first way. That's fine. I'll mark this not as a bug.
